import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";


import Footer from "~/components/footer";
import NavBar from "~/components/navBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Neff Starter",
  description: "Generated by /@Neffrey/neff-starter",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
